import { StaticPage } from "@/components/StaticPage";

export const metadata = { title: "Terms of Use . The Mayoral Record" };

export default function Terms() {
  return (
    <StaticPage title="Terms of Use">
      <h2>What this site is</h2>
      <p>The Mayoral Record is an independent civic-transparency project documenting Toronto's 2026 mayoral race. It is not affiliated with any candidate, campaign, or political party. There is no financial relationship between this project and any candidate.</p>

      <h2>What the content is</h2>
      <ul>
        <li>Records are extracted from public Instagram posts using a documented pipeline. The cited Instagram post (linked from each record) is the primary source. If a record contradicts its cited source, the source wins.</li>
        <li>Council voting records are sourced from the City of Toronto's public voting record. Verified badges indicate cross-references between extracted action records and council votes.</li>
        <li>Synthesis paragraphs and chat answers are generated by an LLM (Claude Opus 4.7 for synthesis, Claude Sonnet 4.6 for chat) using publicly disclosed system prompts. The cited shortcodes within each answer are authoritative.</li>
      </ul>

      <h2>Reader-submitted content</h2>
      <ul>
        <li>Reader queries to the chat are anonymous and aggregate-only.</li>
        <li>Chat answers are generated at request time. They are subject to the limits of language models and may contain errors.</li>
        <li>We may rate-limit or block traffic that appears coordinated or abusive.</li>
        <li>Pol.is deliberations are hosted by Pol.is. Statement moderation is governed by Pol.is's terms.</li>
      </ul>

      <h2>No warranty, no advice</h2>
      <ul>
        <li>The site is provided as-is. No warranty of accuracy, completeness, or fitness for any particular purpose.</li>
        <li>Nothing here is voting advice. It is a sourced record. Make your own decisions.</li>
        <li>Information may be wrong. If you spot an error, please <a href="https://github.com/fullstackvibecoder/thebradfordfiles/issues">open a GitHub issue</a>.</li>
      </ul>

      <h2>Equal-billing rules</h2>
      <p>Candidates are listed alphabetically by surname. No candidate is given visual prominence over any other.</p>

      <h2>Open source</h2>
      <p>The code, the methodology, and the system prompts are open source under the MIT license at <a href="https://github.com/fullstackvibecoder/thebradfordfiles">GitHub</a>.</p>

      <p className="mt-6 bg-stamp-bg border-l-[3px] border-stamp-border p-3 text-[13px]">This is a plain-English statement. It is not legal advice. Last updated: 2026-05-04.</p>
    </StaticPage>
  );
}
